{
 "title": "scibert-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SciBERT Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Успешные запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "predict_requests_total{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Загружена ли модель",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "model_loaded", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время ответа (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(predict_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}